Stage 2: Predicting Length of Stay

In [1]:
import pandas as pd
import numpy as np

In [2]:
#import admisson data
df = pd.read_csv('admission_data.csv')

In [3]:
df

,PID,AGE,GENDER,SMOKING,ALCOHOL,HTN,CAD,PRIOR CMP,HB,TLC,...,VT,PSVT,CONGENITAL,NEURO CARDIOGENIC SYNCOPE,ORTHOSTATIC,CARDIOGENIC SHOCK,SHOCK,PULMONARY EMBOLISM,CHEST INFECTION,TARGET
0,506,50,M,0,0,1,1,0,13.1,10.5,...,0,0,0,0,0,0,0,0,0,4
1,798,71,M,0,0,0,1,0,12.9,8.5,...,0,0,0,0,0,0,0,0,0,2
2,798,71,M,0,0,0,1,0,12.9,8.5,...,0,0,0,0,0,0,0,0,0,2
3,798,72,M,0,0,0,1,0,11.4,6.6,...,0,0,0,0,0,0,0,0,0,6
4,989,71,M,0,0,1,1,0,10.7,14.1,...,0,0,0,0,0,0,0,0,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15752,4888286,68,M,0,0,0,1,0,12.2,6.7,...,0,0,0,0,0,0,0,0,0,5
15753,4888926,65,F,0,0,1,1,0,11.3,11.3,...,0,0,0,0,0,0,0,0,0,2
15754,5711587,60,F,0,0,0,0,1,10.1,9.8,...,0,0,0,0,0,0,0,0,0,11
15755,6408503,68,F,0,0,0,1,0,9.8,17.3,...,0,0,0,0,0,0,1,0,0,11
15756,NILL,30,M,0,0,0,1,0,13.8,10.4,...,0,0,0,0,0,0,0,0,0,5

In [4]:
#find correlation between all the variables
corr_matrix = df.corr()
#remove correlated variables above 0.80
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
# Find features with correlation greater than 0.80
to_drop = [column for column in upper.columns if any(upper[column] > 0.80)]
# Drop features 
df.drop(to_drop, axis=1, inplace=True)

In [5]:
#list unique values in chest infection
df['CHEST INFECTION'].unique()
#drop rows with '\\' in chest infection
df = df[df['CHEST INFECTION'] != '\\']

In [6]:
df.dropna(inplace=True)
df = df[df['PID'] != 'NILL']
df = df[(df != 'EMPTY').all(1)]
df['GENDER'] = np.where(df['GENDER'] == 'M', 1, 0)
#convert PID to int
df['PID'] = df['PID'].astype(int)
#convert HB and TLC to float 
df['HB'] = df['HB'].astype(float)
df['TLC'] = df['TLC'].astype(float)
#convert Platelets, glucose and chest infection to int
# df['PLATELETS'] = df['PLATELETS'].astype(float)
# df['GLUCOSE'] = df['GLUCOSE'].astype(float)
df['CHEST INFECTION'] = df['CHEST INFECTION'].astype(int)

c:\Python\Python376\lib\site-packages\pandas\util\_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

In [7]:
df.dtypes

PID                            int32
AGE                            int64
GENDER                         int32
SMOKING                        int64
ALCOHOL                        int64
HTN                            int64
CAD                            int64
PRIOR CMP                      int64
HB                           float64
TLC                          float64
PLATELETS                     object
GLUCOSE                       object
RAISED CARDIAC ENZYMES         int64
SEVERE ANAEMIA                 int64
ANAEMIA                        int64
STABLE ANGINA                  int64
ACS                            int64
STEMI                          int64
ATYPICAL CHEST PAIN            int64
HEART FAILURE                  int64
VALVULAR                       int64
CHB                            int64
SSS                            int64
AF                             int64
VT                             int64
PSVT                           int64
CONGENITAL                     int64
NEURO CARDIOGENIC SYNCOPE      int64
ORTHOSTATIC                    int64
CARDIOGENIC SHOCK              int64
SHOCK                          int64
PULMONARY EMBOLISM             int64
CHEST INFECTION                int32
TARGET                         int64
dtype: object

In [8]:
#list unique values and counts of PID in descending order
df['PID'].value_counts()
#find range of PID
print(df['PID'].max())
df['PID'].min()

5711587

506

In [9]:
#check if input PID already exists in DF return TARGET variable
def check_pid(pid):
    if pid in df['PID'].values:
        #return mean of all values for PID
        return df[df['PID'] == pid]['TARGET'].mean().round()
    else:
        return 0

In [10]:
#regression model
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

#split data into train and test and drop Target and PID variable from X
X = df.drop(['TARGET'], axis=1)
y = df['TARGET']

In [11]:
#fit the model
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
model = LinearRegression().fit(X_train, y_train)
#predict the model and convert to int 
# y_pred = model.predict(X_test)

In [12]:
#list data types
df.dtypes

PID                            int32
AGE                            int64
GENDER                         int32
SMOKING                        int64
ALCOHOL                        int64
HTN                            int64
CAD                            int64
PRIOR CMP                      int64
HB                           float64
TLC                          float64
PLATELETS                     object
GLUCOSE                       object
RAISED CARDIAC ENZYMES         int64
SEVERE ANAEMIA                 int64
ANAEMIA                        int64
STABLE ANGINA                  int64
ACS                            int64
STEMI                          int64
ATYPICAL CHEST PAIN            int64
HEART FAILURE                  int64
VALVULAR                       int64
CHB                            int64
SSS                            int64
AF                             int64
VT                             int64
PSVT                           int64
CONGENITAL                     int64
NEURO CARDIOGENIC SYNCOPE      int64
ORTHOSTATIC                    int64
CARDIOGENIC SHOCK              int64
SHOCK                          int64
PULMONARY EMBOLISM             int64
CHEST INFECTION                int32
TARGET                         int64
dtype: object

In [13]:
# import tensorflow as tf
# from tensorflow.keras import backend
# from tensorflow.keras import models, regularizers, layers, optimizers, losses, metrics
# from tensorflow.keras import Sequential
# from tensorflow.keras.layers import Dense

In [14]:
# # Training the network
# modell = models.Sequential()
# cols = X_train.shape[1]
# input_shape = (cols,)
# modell.add(layers.Dense(1024, activation='relu', kernel_regularizer=regularizers.l2(0.001), input_shape=input_shape))
# # model.add(layers.BatchNormalization())
# modell.add(layers.Dense(1024, activation='relu', kernel_regularizer=regularizers.l2(0.001)))
# modell.add(layers.Dropout(0.2))
# modell.add(layers.Dense(1024, activation='relu', kernel_regularizer=regularizers.l2(0.001)))
# modell.add(layers.Dropout(0.2))
# modell.add(layers.Dense(1024, activation='relu', kernel_regularizer=regularizers.l2(0.001)))
# modell.add(layers.Dropout(0.2))
# modell.add(layers.Dense(1, activation='relu'))
# print(modell.summary())

# # FIT / TRAIN model on training daa
# NumEpochs = 20
# BatchSize = 8

# X_train = np.asarray(X_train).astype('float32')
# # Compile the model and fit it on the training data
# modell.compile(optimizer=optimizers.Adam(lr=1e-4), loss='mean_absolute_error', metrics=['mae'])
# history = modell.fit(X_train, y_train, epochs=NumEpochs, batch_size=BatchSize, validation_data=(X_test, y_test))

# # Predicting on the test dataset
# results = modell.evaluate(X_test, y_test)
# print("_"*100)
# print("Test Loss and MAE")
# print("results ", results)

In [15]:
from sklearn.metrics import r2_score
from sklearn.metrics import accuracy_score
y_pred = model.predict(X_test).astype(int).round()
y_pred.shape
#call check_pid function to check if PID already exists in DF for every row in y_pred
for i in range(len(X_test)):
    y_pred[i] = ((y_pred[i] + check_pid(X_test.iloc[i]['PID']))/2).round()

print(y_pred)
score = r2_score(y_test, y_pred)
print(score)

[8 9 6 ... 7 8 6]
0.6847353571088057

In [16]:
# #predict the model
# test = np.array([989,71,1,0,0,1,1,0,10.7,14.1,227,253,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
# test = test.reshape(1, -1)
# pid = 989
# y_pred = model.predict(test).astype(int).round()
# ((y_pred[0] + check_pid(pid))/2).round()

In [17]:
#append X_test and y_test to df
df_test = X_test
df_test['LOS'] = y_pred

In [18]:
df_test

,PID,AGE,GENDER,SMOKING,ALCOHOL,HTN,CAD,PRIOR CMP,HB,TLC,...,VT,PSVT,CONGENITAL,NEURO CARDIOGENIC SYNCOPE,ORTHOSTATIC,CARDIOGENIC SHOCK,SHOCK,PULMONARY EMBOLISM,CHEST INFECTION,LOS
12775,602495,82,0,0,0,1,1,0,11.8,10.1,...,0,0,0,0,0,0,0,0,0,8
14935,670926,65,1,0,0,1,1,0,8.7,15.6,...,0,0,0,0,0,0,0,0,0,9
4006,280038,53,0,0,0,1,1,0,13.9,12.5,...,0,0,0,0,0,0,0,0,0,6
15095,675773,62,1,0,0,1,1,0,9.4,16.7,...,0,0,0,0,0,0,0,0,0,8
5078,315883,60,1,0,0,0,0,1,13.8,14.4,...,0,0,0,0,0,0,0,1,0,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6029,351289,66,0,0,0,1,0,1,12.7,9.2,...,0,0,0,0,0,0,0,0,0,6
7660,399243,45,1,0,1,0,0,1,13.8,7.0,...,0,0,0,0,0,0,0,0,0,6
9509,465403,42,1,1,1,1,1,0,16.9,12.6,...,0,0,0,0,0,0,0,0,0,7
8762,438244,60,1,0,0,1,1,0,12.6,8.0,...,0,0,0,0,0,0,0,0,0,8
15709,708611,67,0,0,0,1,1,0,11.1,8.8,...,0,0,0,0,0,0,0,0,0,6

In [19]:
#randomly select 43 rows from df_test
df_test = df_test.sample(n=43)

In [20]:
df_test
#save this to csv
# df_test.to_csv('test.csv')

,PID,AGE,GENDER,SMOKING,ALCOHOL,HTN,CAD,PRIOR CMP,HB,TLC,...,VT,PSVT,CONGENITAL,NEURO CARDIOGENIC SYNCOPE,ORTHOSTATIC,CARDIOGENIC SHOCK,SHOCK,PULMONARY EMBOLISM,CHEST INFECTION,LOS
2796,237678,67,1,0,0,1,0,0,11.5,8.80,...,0,0,0,0,0,0,0,0,0,6
5408,329398,41,1,0,0,1,1,0,14.1,10.20,...,0,0,0,0,0,0,0,0,0,4
5356,326472,65,1,0,0,0,0,1,10.7,8.30,...,0,0,0,0,0,0,0,0,0,6
9621,469963,60,0,0,0,0,1,0,8.1,25.00,...,0,0,0,0,0,0,0,0,0,10
8649,433970,60,1,0,0,0,1,0,15.1,6.30,...,0,0,0,0,0,0,0,0,0,4
3265,256469,65,1,0,0,1,1,0,11.7,9.10,...,0,0,0,0,0,0,0,0,0,7
4361,292597,70,0,0,0,1,1,0,13.1,5.60,...,0,0,0,0,0,0,0,0,0,6
5089,316272,47,0,0,0,0,0,0,9.3,8.10,...,0,0,0,0,0,1,0,0,0,6
10064,484180,72,1,0,0,0,1,0,13.7,7.10,...,0,0,0,0,0,0,0,0,0,2
9058,449225,73,1,0,0,0,1,0,12.5,21.18,...,0,0,0,0,0,0,0,0,0,7
1841,178228,63,0,0,0,1,0,0,8.9,4.00,...,0,0,0,0,0,1,1,0,0,6
2523,218595,80,1,0,0,1,1,0,10.9,7.20,...,1,0,0,0,0,0,0,0,0,12
8095,413730,29,1,0,0,0,0,0,16.9,14.70,...,0,0,0,0,0,0,0,0,0,4
1456,161823,83,1,0,0,1,1,0,11.1,12.50,...,0,0,0,0,0,0,0,0,0,8
15,4650,65,1,0,0,1,1,0,12.9,5.90,...,0,0,0,0,0,0,0,0,0,6
14677,662893,58,1,0,0,1,1,0,12.9,6.60,...,0,0,0,0,0,0,0,0,0,4
5772,342425,57,0,0,0,1,1,1,10.6,15.00,...,0,0,0,0,0,0,0,0,0,8
10761,515953,62,1,0,0,1,1,0,14.4,10.70,...,0,0,0,0,0,0,0,0,0,4
7780,403256,78,0,0,0,1,0,0,7.1,16.50,...,0,0,0,0,0,0,0,0,0,10
12873,605810,45,1,0,0,0,0,0,16.6,14.20,...,0,0,0,0,0,0,0,0,0,6
14288,651109,60,1,0,0,0,0,1,11.4,7.70,...,0,0,0,0,0,1,0,0,0,6
8672,435469,80,0,0,0,0,1,1,11.9,12.10,...,0,0,0,0,0,0,0,0,0,10
744,119455,74,1,0,0,0,0,1,10.7,20.80,...,0,0,0,0,0,0,0,0,0,6
9714,472438,53,1,0,0,0,1,0,15.2,8.90,...,0,0,0,0,0,0,0,0,0,6
1165,153716,60,1,0,0,0,0,1,11.6,14.70,...,0,0,0,0,0,0,0,0,0,7
5397,328874,31,1,0,0,0,0,0,13.2,13.90,...,0,0,0,0,0,0,0,0,0,5
10056,483764,10,1,0,0,0,0,0,16.3,8.90,...,0,0,1,0,0,0,0,0,0,6
9620,469939,59,1,0,0,0,1,1,11.2,11.40,...,0,0,0,0,0,0,0,0,0,6
14122,646625,66,1,0,0,1,1,0,14.5,27.40,...,0,0,0,0,0,0,0,0,1,8
13582,630366,41,1,0,0,1,1,0,15.1,19.60,...,0,0,0,0,0,0,0,0,0,10
819,137588,61,1,0,0,0,1,0,13.3,7.30,...,0,0,0,0,0,0,0,0,0,4
3616,267165,62,1,1,0,1,1,0,14.9,14.90,...,0,0,0,0,0,1,1,0,0,4
470,69823,75,1,0,0,1,1,1,9.8,7.40,...,0,0,0,0,0,0,0,0,0,11
15660,699413,75,0,0,0,0,0,0,11.8,8.20,...,0,0,0,0,0,0,0,0,0,4
4289,289261,39,1,0,0,0,1,0,14.9,14.20,...,0,0,0,0,0,0,0,0,0,4
8842,440763,57,0,0,0,0,1,0,13.3,4.30,...,0,0,0,0,0,0,0,0,0,3
1190,154029,4,1,0,0,1,1,0,14.6,8.70,...,0,0,0,0,0,0,0,0,0,9
6376,361877,70,0,0,0,0,0,0,10.3,9.30,...,0,0,0,0,0,0,0,0,0,10
12842,604899,66,0,0,0,0,0,0,10.6,15.80,...,0,0,0,0,0,0,0,0,0,6
7942,409156,37,1,1,0,0,1,0,13.4,10.00,...,0,0,0,0,0,0,0,0,0,9
5128,317758,75,1,0,0,0,1,0,11.3,10.30,...,0,0,0,0,0,0,0,0,0,8
6688,372647,73,1,0,0,0,1,0,13.3,11.40,...,0,0,0,0,0,0,0,0,0,6
12835,604843,60,1,0,1,1,1,0,11.9,17.10,...,0,0,0,0,0,0,0,0,0,6

In [21]:
#read isAdmitted data
import pandas as pd
df_admitted = pd.read_csv('isAdmitted.csv')
df_admitted.drop(['Unnamed: 0'], axis=1, inplace=True)
df_admitted

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Predicted,Urgency Score
0,60,1,4,130,206,0,2,132,1,2.4,2,2,7,1,98.196249
1,51,1,4,140,298,0,0,122,1,4.2,2,3,7,1,96.321198
2,46,1,4,140,311,0,0,120,1,1.8,2,2,7,1,95.592806
3,56,0,4,134,409,0,2,150,1,1.9,2,2,7,1,95.289008
4,67,1,4,120,229,0,2,129,1,2.6,2,2,7,1,95.258880
5,54,1,4,124,266,0,2,109,1,2.2,2,1,7,1,94.663355
6,53,1,4,123,282,0,0,95,1,2.0,2,2,7,1,94.130874
7,59,1,4,110,239,0,2,142,1,1.2,2,1,7,1,94.037527
8,62,1,4,120,267,0,0,99,1,1.8,2,2,7,1,90.539153
9,57,1,4,165,289,1,2,124,0,1.0,2,3,7,1,90.371228
10,62,1,3,130,231,0,0,146,0,1.8,2,3,7,1,90.272429
11,60,1,4,140,293,0,2,170,0,1.2,2,2,7,1,89.932533
12,64,0,4,130,303,0,0,122,0,2.0,2,2,3,1,89.660817
13,43,0,4,132,341,1,2,136,1,3.0,2,0,7,1,88.276600
14,54,1,4,120,188,0,0,113,0,1.4,2,1,7,1,84.640350
15,69,1,3,140,254,0,2,146,0,2.0,2,3,7,1,84.280228
16,56,1,4,125,249,1,2,144,1,1.2,2,1,3,1,81.881071
17,59,1,4,170,326,0,2,140,1,3.4,3,0,7,1,81.574357
18,70,1,3,160,269,0,0,112,1,2.9,2,1,7,1,80.848525
19,66,0,4,178,228,1,0,165,1,1.0,2,2,7,1,80.580270
20,59,1,3,126,218,1,0,134,0,2.2,2,1,6,1,79.428067
21,61,0,4,145,307,0,2,146,1,1.0,2,0,7,1,79.333935
22,50,1,4,150,243,0,2,128,0,2.6,2,0,7,1,78.000626
23,55,0,4,180,327,0,1,117,1,3.4,2,0,3,1,74.939497
24,45,1,4,142,309,0,2,147,1,0.0,2,3,7,1,74.222421
25,62,1,2,120,281,0,2,103,0,1.4,2,1,7,1,73.135908
26,58,1,4,125,300,0,2,171,0,0.0,1,2,7,1,71.191525
27,52,1,4,108,233,1,0,147,0,0.1,1,3,7,1,69.851122
28,58,1,4,100,234,0,0,156,0,0.1,1,1,7,1,64.141462
29,59,1,4,140,177,0,0,162,1,0.0,1,1,7,1,63.884073
30,77,1,4,125,304,0,2,162,1,0.0,1,3,3,1,63.394591
31,62,0,3,130,263,0,0,97,0,1.2,2,1,7,1,62.129874
32,64,1,1,110,211,0,2,144,1,1.8,2,0,3,1,61.223483
33,45,1,4,104,208,0,2,148,1,3.0,2,0,3,1,60.510080
34,68,1,3,180,274,1,2,150,1,1.6,2,0,7,1,60.159019
35,68,1,3,118,277,0,0,151,0,1.0,1,1,7,1,59.270633
36,46,1,4,120,249,0,2,144,0,0.8,1,0,7,1,58.935861
37,58,1,3,105,240,0,2,154,1,0.6,2,0,7,1,55.305485
38,69,0,1,140,239,0,0,151,0,1.8,1,2,3,1,55.114790
39,51,1,3,94,227,0,0,154,1,0.0,1,1,7,1,54.938347
40,67,0,4,106,223,0,0,142,0,0.3,1,2,3,1,54.504916
41,61,1,3,150,243,1,0,137,1,1.0,2,0,3,1,52.628913
42,63,1,1,145,233,1,2,150,0,2.3,3,0,6,1,50.768943

In [22]:
PID = df_test['PID']
PID = PID.to_numpy()

#append PID to df_admitted
df_admitted['PID'] = PID

In [23]:
df_admitted

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Predicted,Urgency Score,PID
0,60,1,4,130,206,0,2,132,1,2.4,2,2,7,1,98.196249,237678
1,51,1,4,140,298,0,0,122,1,4.2,2,3,7,1,96.321198,329398
2,46,1,4,140,311,0,0,120,1,1.8,2,2,7,1,95.592806,326472
3,56,0,4,134,409,0,2,150,1,1.9,2,2,7,1,95.289008,469963
4,67,1,4,120,229,0,2,129,1,2.6,2,2,7,1,95.258880,433970
5,54,1,4,124,266,0,2,109,1,2.2,2,1,7,1,94.663355,256469
6,53,1,4,123,282,0,0,95,1,2.0,2,2,7,1,94.130874,292597
7,59,1,4,110,239,0,2,142,1,1.2,2,1,7,1,94.037527,316272
8,62,1,4,120,267,0,0,99,1,1.8,2,2,7,1,90.539153,484180
9,57,1,4,165,289,1,2,124,0,1.0,2,3,7,1,90.371228,449225
10,62,1,3,130,231,0,0,146,0,1.8,2,3,7,1,90.272429,178228
11,60,1,4,140,293,0,2,170,0,1.2,2,2,7,1,89.932533,218595
12,64,0,4,130,303,0,0,122,0,2.0,2,2,3,1,89.660817,413730
13,43,0,4,132,341,1,2,136,1,3.0,2,0,7,1,88.276600,161823
14,54,1,4,120,188,0,0,113,0,1.4,2,1,7,1,84.640350,4650
15,69,1,3,140,254,0,2,146,0,2.0,2,3,7,1,84.280228,662893
16,56,1,4,125,249,1,2,144,1,1.2,2,1,3,1,81.881071,342425
17,59,1,4,170,326,0,2,140,1,3.4,3,0,7,1,81.574357,515953
18,70,1,3,160,269,0,0,112,1,2.9,2,1,7,1,80.848525,403256
19,66,0,4,178,228,1,0,165,1,1.0,2,2,7,1,80.580270,605810
20,59,1,3,126,218,1,0,134,0,2.2,2,1,6,1,79.428067,651109
21,61,0,4,145,307,0,2,146,1,1.0,2,0,7,1,79.333935,435469
22,50,1,4,150,243,0,2,128,0,2.6,2,0,7,1,78.000626,119455
23,55,0,4,180,327,0,1,117,1,3.4,2,0,3,1,74.939497,472438
24,45,1,4,142,309,0,2,147,1,0.0,2,3,7,1,74.222421,153716
25,62,1,2,120,281,0,2,103,0,1.4,2,1,7,1,73.135908,328874
26,58,1,4,125,300,0,2,171,0,0.0,1,2,7,1,71.191525,483764
27,52,1,4,108,233,1,0,147,0,0.1,1,3,7,1,69.851122,469939
28,58,1,4,100,234,0,0,156,0,0.1,1,1,7,1,64.141462,646625
29,59,1,4,140,177,0,0,162,1,0.0,1,1,7,1,63.884073,630366
30,77,1,4,125,304,0,2,162,1,0.0,1,3,3,1,63.394591,137588
31,62,0,3,130,263,0,0,97,0,1.2,2,1,7,1,62.129874,267165
32,64,1,1,110,211,0,2,144,1,1.8,2,0,3,1,61.223483,69823
33,45,1,4,104,208,0,2,148,1,3.0,2,0,3,1,60.510080,699413
34,68,1,3,180,274,1,2,150,1,1.6,2,0,7,1,60.159019,289261
35,68,1,3,118,277,0,0,151,0,1.0,1,1,7,1,59.270633,440763
36,46,1,4,120,249,0,2,144,0,0.8,1,0,7,1,58.935861,154029
37,58,1,3,105,240,0,2,154,1,0.6,2,0,7,1,55.305485,361877
38,69,0,1,140,239,0,0,151,0,1.8,1,2,3,1,55.114790,604899
39,51,1,3,94,227,0,0,154,1,0.0,1,1,7,1,54.938347,409156
40,67,0,4,106,223,0,0,142,0,0.3,1,2,3,1,54.504916,317758
41,61,1,3,150,243,1,0,137,1,1.0,2,0,3,1,52.628913,372647
42,63,1,1,145,233,1,2,150,0,2.3,3,0,6,1,50.768943,604843

In [24]:
#merge df_test and df_admitted
df_test = pd.merge(df_test, df_admitted, on='PID', how='right')

In [25]:
df_test['Length of Stay'] = df_test['LOS']

In [26]:
df_test.drop(['LOS'], axis=1, inplace=True)
df_test
#save as csv
df_test.to_csv('patientDashboard.csv')

In [27]:
#make a df using PID, LOS and urgency score
df_test = df_test[['PID', 'Length of Stay', 'Urgency Score']]
df_test
#save into csv without index
df_test.to_csv('bedForecast.csv', index=False)

In [28]:

import pickle
pickle.dump(model, open('model_los.pkl','wb'))

Stage 3: Estimating number of beds

In [29]:
def sort_queue(df):
    df = df.sort_values(by=['Urgency Score'], ascending=False)
    return df

In [30]:
totalbeds = 450
filledbeds = 420

#queue of urgency score and LOS only 20 rows from df_test
new = 0
new+=20
queue = df_test[['Urgency Score', 'Length of Stay']].head(new).to_numpy()

#add another column with value 0
queue = np.insert(queue, 2, 0, axis=1)
beds = np.zeros(450)
#make 400 in beds 1
for i in range(filledbeds):
    beds[i] = 1
i+=1
days = 1
while True: #real time
    print("Day No.: ",days)
    
    #decrement LOS by 1 for every patient with a bed
    for j in range(len(queue)):
        if queue[j,2] == 1:
            queue[j,1] -= 1
            #keep max of 0 or queue[j,1]
            if queue[j,1] < 0:
                queue[j,1] = 0
            #if LOS is 0, release the bed
            if queue[j,1] == 0:
                print("Released bed is: ", j+1)
                # beds[filledbeds+j] = 0
                i-=1
                queue[j,2] = -1 #discharged

    print("No. of beds available: ",450-i)
    #check if any patient does not have a bed and find the patient with highest urgency score
    while True:
        if i < 450:
            for j in range(len(queue)):
                if queue[j,2] == 0:
                    maxi = j
                    break
            if queue[maxi,2] == 0:
                # beds[i] = 1
                queue[maxi,2] = 1
                print("Bed filled for patient: ", maxi+1, " with urgency score: ", queue[maxi,0])
                i+=1
                #end loop if all patients are discharged
                if np.count_nonzero(queue[:,2] == 1) + np.count_nonzero(queue[:,2] == -1) == len(queue):
                    break
        else:
            break
    # print(queue)
    
    #print a new line
    print()
    days+=1
    #select next 10 rows from df_test
    if (new > len(df_test)):
        queue_new = df_test[['Urgency Score', 'Length of Stay']].iloc[new:].to_numpy()
        queue_new = np.insert(queue_new, 2, 0, axis=1)
        queue = np.concatenate((queue, queue_new), axis=0)
        
    else:
        queue_new = df_test[['Urgency Score', 'Length of Stay']].iloc[new:new+10].to_numpy()
        queue_new = np.insert(queue_new, 2, 0, axis=1)
        queue = np.concatenate((queue, queue_new), axis=0)
        new+=10
    
    #check if queue[:,2] is all 1 or -1
    if np.count_nonzero(queue[:,2] == 1) + np.count_nonzero(queue[:,2] == -1) == len(queue):
        break

print(days-1)

Day No.:  1
No. of beds available:  30
Bed filled for patient:  1  with urgency score:  98.1962492038868
Bed filled for patient:  2  with urgency score:  96.32119803160218
Bed filled for patient:  3  with urgency score:  95.59280607599857
Bed filled for patient:  4  with urgency score:  95.289008039144
Bed filled for patient:  5  with urgency score:  95.258880206613
Bed filled for patient:  6  with urgency score:  94.6633547229964
Bed filled for patient:  7  with urgency score:  94.13087362618874
Bed filled for patient:  8  with urgency score:  94.0375272857432
Bed filled for patient:  9  with urgency score:  90.53915293802962
Bed filled for patient:  10  with urgency score:  90.37122817348585
Bed filled for patient:  11  with urgency score:  90.27242931335893
Bed filled for patient:  12  with urgency score:  89.93253277084598
Bed filled for patient:  13  with urgency score:  89.66081700395102
Bed filled for patient:  14  with urgency score:  88.2766000178473
Bed filled for patient:  15  with urgency score:  84.64035016417408
Bed filled for patient:  16  with urgency score:  84.28022840834298
Bed filled for patient:  17  with urgency score:  81.88107054642381
Bed filled for patient:  18  with urgency score:  81.57435650225085
Bed filled for patient:  19  with urgency score:  80.84852509468678
Bed filled for patient:  20  with urgency score:  80.58027020485687

Day No.:  2
No. of beds available:  10
Bed filled for patient:  21  with urgency score:  79.42806725278344
Bed filled for patient:  22  with urgency score:  79.3339348628328
Bed filled for patient:  23  with urgency score:  78.00062643266396
Bed filled for patient:  24  with urgency score:  74.93949748112396
Bed filled for patient:  25  with urgency score:  74.22242065119579
Bed filled for patient:  26  with urgency score:  73.13590820902574
Bed filled for patient:  27  with urgency score:  71.19152544092556
Bed filled for patient:  28  with urgency score:  69.85112160789303
Bed filled for patient:  29  with urgency score:  64.14146201047019
Bed filled for patient:  30  with urgency score:  63.88407321309408

Day No.:  3
Released bed is:  9
No. of beds available:  1
Bed filled for patient:  31  with urgency score:  63.39459116738394

Day No.:  4
No. of beds available:  0

Day No.:  5
Released bed is:  2
Released bed is:  5
Released bed is:  13
Released bed is:  16
Released bed is:  18
No. of beds available:  5
Bed filled for patient:  32  with urgency score:  62.12987425194808
Bed filled for patient:  33  with urgency score:  61.223483049953664
Bed filled for patient:  34  with urgency score:  60.510079755004185
Bed filled for patient:  35  with urgency score:  60.15901933190505
Bed filled for patient:  36  with urgency score:  59.27063278920779

Day No.:  6
No. of beds available:  0

Day No.:  7
Released bed is:  1
Released bed is:  3
Released bed is:  7
Released bed is:  8
Released bed is:  11
Released bed is:  15
Released bed is:  20
Released bed is:  26
Released bed is:  31
No. of beds available:  9
Bed filled for patient:  37  with urgency score:  58.93586055995913
Bed filled for patient:  38  with urgency score:  55.30548524872994
Bed filled for patient:  39  with urgency score:  55.114790352515605
Bed filled for patient:  40  with urgency score:  54.93834684148924
Bed filled for patient:  41  with urgency score:  54.50491588839017
Bed filled for patient:  42  with urgency score:  52.62891277577438
Bed filled for patient:  43  with urgency score:  50.76894250092157

7